on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn global add vsce
    - name: Set tag to env if tag event
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "EXTENSION_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set tag to env if not tag event
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: echo "EXTENSION_VERSION=0.0.0" >> $GITHUB_ENV
    - name: Set version to package.json
      run: sed -i -e "s/EXTENSION_VERSION/$EXTENSION_VERSION/g" package.json
    - run: vsce package --yarn
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*.vsix'
